import type { RenderInput } from "@motn/schema";

// Studio fixture: a hand-written RenderInput so component work never needs
// the pipeline. `sample.mp4` in public/ is generated by scripts/make-fixture.sh.

const SCRIPT =
  "Here is the thing nobody tells you about making videos. 87 percent of channels that post one hundred videos cross one thousand subscribers. First, pick one topic. Second, keep a schedule. Third, study retention weekly. Do that and you beat almost everyone.";

const words = (() => {
  const tokens = SCRIPT.split(" ");
  const out: RenderInput["words"] = [];
  let t = 500;
  tokens.forEach((text, i) => {
    const dur = 200 + text.length * 40;
    out.push({ i, text, startMs: t, endMs: t + dur - 40 });
    t += dur + (/[.!?]$/.test(text) ? 350 : 30);
  });
  return out;
})();

const durationMs = Math.max(30000, (words.at(-1)?.endMs ?? 29000) + 1000);

export const sampleRenderInput: RenderInput = {
  videoSrc: "sample.mp4",
  words,
  plan: {
    schemaVersion: 1,
    language: "en",
    provenance: { promptVersion: "fixture@1", model: "fixture", schemaVersion: 1 },
    source: { durationMs, fps: 30, width: 1080, height: 1920 },
    style: { theme: "editorial-dark", motionIntensity: "punchy" },
    captions: {
      enabled: true,
      position: "bottom",
      preset: "punchy",
      emphases: [
        { wordIndex: 3, effect: "color" },
        { wordIndex: 10, effect: "scale" },
        { wordIndex: 20, effect: "color" },
      ],
      emojiInserts: [{ afterWordIndex: 12, emoji: "📈" }],
    },
    scenes: (() => {
      const wEnd = words.length - 1;
      const ms = (wi: number, edge: "s" | "e") =>
        edge === "s" ? words[wi]!.startMs : words[wi]!.endMs;
      return [
        {
          id: "s1",
          startWordIndex: 0,
          endWordIndex: 9,
          startMs: 0,
          endMs: ms(10, "s"),
          layout: "talking-head-full" as const,
          splitConfig: null,
          talkingHead: { zoom: "punch-in" as const },
          transitionIn: "cut" as const,
          graphic: {
            component: "hookTitle" as const,
            props: { title: "NOBODY TELLS YOU THIS", subtitle: null },
            assets: [],
            enter: "pop" as const,
            exit: "fade" as const,
          },
          rationale: "hook",
        },
        {
          id: "s2",
          startWordIndex: 10,
          endWordIndex: 21,
          startMs: ms(10, "s"),
          endMs: ms(22, "s"),
          layout: "split" as const,
          splitConfig: { side: "top" as const, ratio: 0.45 },
          talkingHead: { zoom: "none" as const },
          transitionIn: "slide" as const,
          graphic: {
            component: "statCounter" as const,
            props: {
              value: 87,
              prefix: null,
              suffix: "%",
              label: "of consistent channels cross 1k subs",
              triggerWordIndex: 10,
            },
            assets: [],
            enter: "pop" as const,
            exit: "fade" as const,
          },
          rationale: "stat",
        },
        {
          id: "s3",
          startWordIndex: 22,
          endWordIndex: 35,
          startMs: ms(22, "s"),
          endMs: ms(36, "s"),
          layout: "split" as const,
          splitConfig: { side: "top" as const, ratio: 0.45 },
          talkingHead: { zoom: "none" as const },
          transitionIn: "slide" as const,
          graphic: {
            component: "listReveal" as const,
            props: {
              title: "The system",
              items: [
                { text: "Pick one topic", triggerWordIndex: 22 },
                { text: "Keep a schedule", triggerWordIndex: 27 },
                { text: "Study retention weekly", triggerWordIndex: 31 },
              ],
            },
            assets: [],
            enter: "slide-up" as const,
            exit: "fade" as const,
          },
          rationale: "list",
        },
        {
          id: "s4",
          startWordIndex: 36,
          endWordIndex: wEnd,
          startMs: ms(36, "s"),
          endMs: durationMs,
          layout: "talking-head-full" as const,
          splitConfig: null,
          talkingHead: { zoom: "slow-in" as const },
          transitionIn: "fade" as const,
          graphic: {
            component: "kineticText" as const,
            props: { text: "BEAT ALMOST EVERYONE", triggerWordIndex: 40 },
            assets: [],
            enter: "pop" as const,
            exit: "fade" as const,
          },
          rationale: "payoff",
        },
      ];
    })(),
  },
};
